/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopologyRouteImport } from './routes/topology'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FirmwareRouteImport } from './routes/firmware'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantsIndexRouteImport } from './routes/tenants/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as DevicesIndexRouteImport } from './routes/devices/index'
import { Route as DevicesDeviceIdRouteImport } from './routes/devices/$deviceId'

const TopologyRoute = TopologyRouteImport.update({
  id: '/topology',
  path: '/topology',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmwareRoute = FirmwareRouteImport.update({
  id: '/firmware',
  path: '/firmware',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsIndexRoute = TenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesIndexRoute = DevicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevicesRoute,
} as any)
const DevicesDeviceIdRoute = DevicesDeviceIdRouteImport.update({
  id: '/$deviceId',
  path: '/$deviceId',
  getParentRoute: () => DevicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/devices': typeof DevicesRouteWithChildren
  '/firmware': typeof FirmwareRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/topology': typeof TopologyRoute
  '/devices/$deviceId': typeof DevicesDeviceIdRoute
  '/devices/': typeof DevicesIndexRoute
  '/events/': typeof EventsIndexRoute
  '/tenants/': typeof TenantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/firmware': typeof FirmwareRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/topology': typeof TopologyRoute
  '/devices/$deviceId': typeof DevicesDeviceIdRoute
  '/devices': typeof DevicesIndexRoute
  '/events': typeof EventsIndexRoute
  '/tenants': typeof TenantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/devices': typeof DevicesRouteWithChildren
  '/firmware': typeof FirmwareRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/topology': typeof TopologyRoute
  '/devices/$deviceId': typeof DevicesDeviceIdRoute
  '/devices/': typeof DevicesIndexRoute
  '/events/': typeof EventsIndexRoute
  '/tenants/': typeof TenantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/devices'
    | '/firmware'
    | '/login'
    | '/notes'
    | '/settings'
    | '/topology'
    | '/devices/$deviceId'
    | '/devices/'
    | '/events/'
    | '/tenants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/firmware'
    | '/login'
    | '/notes'
    | '/settings'
    | '/topology'
    | '/devices/$deviceId'
    | '/devices'
    | '/events'
    | '/tenants'
  id:
    | '__root__'
    | '/'
    | '/devices'
    | '/firmware'
    | '/login'
    | '/notes'
    | '/settings'
    | '/topology'
    | '/devices/$deviceId'
    | '/devices/'
    | '/events/'
    | '/tenants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevicesRoute: typeof DevicesRouteWithChildren
  FirmwareRoute: typeof FirmwareRoute
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRoute
  SettingsRoute: typeof SettingsRoute
  TopologyRoute: typeof TopologyRoute
  EventsIndexRoute: typeof EventsIndexRoute
  TenantsIndexRoute: typeof TenantsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topology': {
      id: '/topology'
      path: '/topology'
      fullPath: '/topology'
      preLoaderRoute: typeof TopologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firmware': {
      id: '/firmware'
      path: '/firmware'
      fullPath: '/firmware'
      preLoaderRoute: typeof FirmwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/': {
      id: '/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof TenantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices/': {
      id: '/devices/'
      path: '/'
      fullPath: '/devices/'
      preLoaderRoute: typeof DevicesIndexRouteImport
      parentRoute: typeof DevicesRoute
    }
    '/devices/$deviceId': {
      id: '/devices/$deviceId'
      path: '/$deviceId'
      fullPath: '/devices/$deviceId'
      preLoaderRoute: typeof DevicesDeviceIdRouteImport
      parentRoute: typeof DevicesRoute
    }
  }
}

interface DevicesRouteChildren {
  DevicesDeviceIdRoute: typeof DevicesDeviceIdRoute
  DevicesIndexRoute: typeof DevicesIndexRoute
}

const DevicesRouteChildren: DevicesRouteChildren = {
  DevicesDeviceIdRoute: DevicesDeviceIdRoute,
  DevicesIndexRoute: DevicesIndexRoute,
}

const DevicesRouteWithChildren =
  DevicesRoute._addFileChildren(DevicesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevicesRoute: DevicesRouteWithChildren,
  FirmwareRoute: FirmwareRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRoute,
  SettingsRoute: SettingsRoute,
  TopologyRoute: TopologyRoute,
  EventsIndexRoute: EventsIndexRoute,
  TenantsIndexRoute: TenantsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
